import ast
import os
from pathlib import Path

def parse_python_file(file_path):
    with open(file_path, "r", encoding="utf-8") as f:
        try:
            tree = ast.parse(f.read())
        except Exception as e:
            print(f"Error parsing {file_path}: {e}")
            return None
    
    info = {
        "imports": [],
        "classes": [],
        "functions": [],
        "docstring": ast.get_docstring(tree) or "No description."
    }
    
    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            for n in node.names:
                info["imports"].append(n.name)
        elif isinstance(node, ast.ImportFrom):
            module = node.module or ""
            for n in node.names:
                info["imports"].append(f"{module}.{n.name}")
        elif isinstance(node, ast.ClassDef):
            info["classes"].append(node.name)
        elif isinstance(node, ast.FunctionDef):
            if not node.name.startswith("_"):
                info["functions"].append(node.name)
                
    return info

def generate_obsidian_map(src_root, output_dir):
    src_root = Path(src_root)
    output_dir = Path(output_dir)
    
    for root, _, files in os.walk(src_root):
        for file in files:
            if file.endswith(".py") and file != "__init__.py":
                rel_path = Path(root).relative_to(src_root) / file
                full_path = Path(root) / file
                
                info = parse_python_file(full_path)
                if not info:
                    continue
                
                md_filename = str(rel_path).replace("/", ".").replace(".py", ".md")
                md_path = output_dir / md_filename
                
                with open(md_path, "w", encoding="utf-8") as f:
                    f.write(f"# Module: {rel_path}\n\n")
                    f.write(f"## 📝 Description\n{info['docstring']}\n\n")
                    
                    if info["classes"]:
                        f.write("## 🏛️ Classes\n")
                        for cls in info["classes"]:
                            f.write(f"- `{cls}`\n")
                        f.write("\n")
                        
                    if info["functions"]:
                        f.write("## 🛠️ Functions\n")
                        for func in info["functions"]:
                            f.write(f"- `{func}`\n")
                        f.write("\n")
                    
                    f.write("## 🔗 Dependencies (Imports)\n")
                    for imp in info["imports"]:
                        # Convert internal imports to wikilinks if they look like our project structure
                        if imp.startswith("src.") or imp.startswith("pipeline.src."):
                            clean_imp = imp.replace("pipeline.src.", "src.")
                            # Estimate the file path for the wikilink
                            parts = clean_imp.split(".")
                            if len(parts) > 1:
                                link_name = ".".join(parts[1:]) + ".md"
                                f.write(f"- [[{link_name}|{imp}]]\n")
                            else:
                                f.write(f"- `{imp}`\n")
                        else:
                            f.write(f"- `{imp}`\n")
                    
                    f.write("\n---\n*Auto-generated by FX Regime Lab Obsidian Mapper*")

if __name__ == "__main__":
    PROJECT_ROOT = "/home/shreyash/fx_regime_lab/fx-regime-lab"
    SRC_DIR = f"{PROJECT_ROOT}/pipeline/src"
    OUT_DIR = f"{PROJECT_ROOT}/_docs/architecture"
    
    generate_obsidian_map(SRC_DIR, OUT_DIR)
    print(f"Generated architecture map in {OUT_DIR}")
