#!/usr/bin/env python3
"""
Emit site/assets/supabase-env.js from SUPABASE_URL + SUPABASE_ANON_KEY (build-time only).
Run on Cloudflare before wrangler deploy; keys stay out of git.
"""
from __future__ import annotations

import json
import os
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / "site" / "assets" / "supabase-env.js"


def main() -> None:
    url = os.environ.get("SUPABASE_URL", "").strip()
    key = os.environ.get("SUPABASE_ANON_KEY", "").strip()
    OUT.parent.mkdir(parents=True, exist_ok=True)
    body = "\n".join(
        [
            "// Generated by scripts/dev/emit_supabase_env_for_site.py — do not edit by hand",
            f"window.__SUPABASE_URL__ = {json.dumps(url)};",
            f"window.__SUPABASE_ANON_KEY__ = {json.dumps(key)};",
            "",
        ]
    )
    OUT.write_text(body, encoding="utf-8")
    print(f"Wrote {OUT} (url set: {bool(url)}, key set: {bool(key)})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
