-- P1-T3: Audit Trail Schema (correlation_id, write_hash, pipeline_errors)
-- Provides deterministic tamper-evident hashing for regime calls and
-- structured error capture for pipeline observability.
-- Dependencies: 20260508000001_p0_validation_immutability.sql (regime_calls, audit_log)

-- ---------------------------------------------------------------------------
-- 1. Regime calls audit columns
-- ---------------------------------------------------------------------------

ALTER TABLE regime_calls
    ADD COLUMN IF NOT EXISTS correlation_id TEXT,
    ADD COLUMN IF NOT EXISTS write_hash    TEXT;

-- Index for tracing a single pipeline run
CREATE INDEX IF NOT EXISTS idx_regime_calls_correlation_id
    ON regime_calls (correlation_id);

-- ---------------------------------------------------------------------------
-- 2. Structured pipeline error log
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS pipeline_errors (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at      TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    step            TEXT NOT NULL,
    error_type      TEXT NOT NULL,
    message         TEXT NOT NULL,
    traceback       TEXT,
    correlation_id  TEXT,
    run_date        DATE
);

COMMENT ON TABLE pipeline_errors IS
    'Structured error log for every pipeline exception.  Not RLS-exposed.';

CREATE INDEX IF NOT EXISTS idx_pipeline_errors_created_at
    ON pipeline_errors (created_at DESC);

CREATE INDEX IF NOT EXISTS idx_pipeline_errors_correlation_id
    ON pipeline_errors (correlation_id);

CREATE INDEX IF NOT EXISTS idx_pipeline_errors_run_date
    ON pipeline_errors (run_date DESC);
