"""Discrete Layer 1 regime labels (Chamber 1)."""

from __future__ import annotations

from enum import StrEnum


class FxRegime(StrEnum):
    """Deterministic regime gate labels persisted to ``regime_calls.regime``."""

    USD_POLICY_BREAKOUT = "USD_POLICY_BREAKOUT"
    CARRY_COLLAPSE = "CARRY_COLLAPSE"
    GROWTH_SURPRISE_USD = "GROWTH_SURPRISE_USD"
    LIQUIDITY_SHOCK = "LIQUIDITY_SHOCK"
    RISK_OFF_DOLLAR_BID = "RISK_OFF_DOLLAR_BID"
    RISK_ON_DOLLAR_OFF = "RISK_ON_DOLLAR_OFF"
    NEUTRAL = "NEUTRAL"
    INR_DEPRECIATION_STRONG = "INR_DEPRECIATION_STRONG"
    INR_DEPRECIATION_MODERATE = "INR_DEPRECIATION_MODERATE"
    INR_NEUTRAL = "INR_NEUTRAL"
    INR_APPRECIATION_MODERATE = "INR_APPRECIATION_MODERATE"
    INR_APPRECIATION_STRONG = "INR_APPRECIATION_STRONG"
